module.exports = {
  endOfLine: 'lf',
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^prop-types',
    '^(next/(.*)$)|^(next$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@/mui/(.*)$',
    '^types$',
    '^@/types/(.*)$',
    '^@/config/(.*)$',
    '^@/lib/(.*)$',
    '^@/_mock/(.*)$',
    '^@/app/(.*)$',
    '^@/assets/(.*)$',
    '^@/auth/(.*)$',
    '^@/components/(.*)$',
    '^@/contexts/(.*)$',
    '^@/hooks/(.*)$',
    '^@/layouts/(.*)$',
    '^@/redux/(.*)$',
    '^@/routes/(.*)$',
    '^@/sections/(.*)$',
    '^@/services/(.*)$',
    '^@/theme/(.*)$',
    '^@/utils/(.*)$',
    '',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['js', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ['prettier-plugin-svelte', '@ianvs/prettier-plugin-sort-imports'],
  pluginSearchDirs: false,
}
